### ISSUE TITLE
HTML module from 3.2/3.4

### ISSUE THREAD

**Issue by frozencemetery** [naftaliharris/placeholder#57]
Hi, it would be great if the new [HTML](https://docs.python.org/3.5/library/html.html) functions (specifically, `escape` and `unescape`) could be exported.

Thanks!

**Comment by naftaliharris** [comment]
That looks probably straightforward. Out of curiosity, what's your interest in those?

**Comment by naftaliharris** [comment]
Done, enjoy! :-)

**Comment by naftaliharris** [comment]
`html` wasn't actually being installed when you'd run "make install"; fixed in #59. Sorry!

(You *could* access `html` from the compiled binary, but you'd lose it when you'd install).

**Comment by naftaliharris** [comment]
Ha this is actually pretty useful, I'm using it now to escape html for code snippets on my blog.

**Comment by frozencemetery** [comment]
> Out of curiosity, what's your interest in those?

I'm mostly after `unescape()`, though `escape()` is useful to have as well.  It's very handy for displaying information served over HTTP.  And implementing a function to do this correctly is not straightforward, but of course moving to python3 introduces all the string/bytestring/encoding behaviors...
